### ISSUE TITLE
Autocomplete support

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#1093]
## What is autocomplete ?

[Autocomplete](https://www.algolia.com/doc/ui-libraries/autocomplete/introduction/what-is-autocomplete/) is a tool created by algolia.

> Autocomplete is an [open source](https://github.com/algolia/autocomplete), production-ready JavaScript library for building autocomplete experiences.

## Support

Currently, it is not possible to use Meilisearch with autocomplete. Our searchClient is not compatible, and we are missing a key method: `getMeilisearchResults`. 

Nonetheless, `autocomplete` is done so that, if we want, we can provide our own client and required methods.

## What do we need

More than just the required methods, more is needed to create the meilisearch-autocomplete tool. This is the extended list

- [x] new `@meilisearch/autocomplete-client` package with its config (eslint, etc...) #971
- [x] compatible search client #971 
- [x] `getMeilisearchResults` method #971 
- [x] Add autocomplete in the user agent sent to Meilisearch #971 
- [x] Tests #971 
- [x] Readme of autocomplete package
- [x] Check plugin compatibility
- [x] Contributing guide
- [x] CI that tests autocomplete only when autocomplete files are changed
- [x] CI that tests autocomplete when instant-meilisearch files are changed since it is a dependency of autocomplete
- [x] Script that automatically changes the version in package-version.ts when the version in the package.json is changed. [See example](https://github.com/meilisearch/instant-meilisearch/blob/ed92bd2f1c223026d6ba2b9163a8fbea32fd093e/packages/instant-meilisearch/package.json#L34)
- [ ] Change the root readme to a readme that contains all the packages present in this repo

**Comment by bidoubiwa** [comment]
fixed by: #971
