### ISSUE TITLE
Use changeset to handle publishing of packages

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#959]
With the migration to #939 we need to change the way we handle publishes on github but also on `npm`. 

The tool [suggested by turborepo](https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing) is changeset. 

Changeset automates a lot of the tedious actions, for example updating the version manually or creating relevant information on what the PR does.

## Changeset 
Changing to changeset requires the contributor to add a [`changeset`](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) in its PR. A changeset A changeset is a piece of information about changes made in a branch or commit. It generates a unique file containing different information.

For example: 
```
---
"@meilisearch/instant-meilisearch": minor
---

I did something in this PR
```

## Version Update

When running `changeset version` all the files are merged into the CHANGELOG of the related package. In the case above it updates (or creates) the CHANGELOG of the `@meilisearch/instant-meilisearch` package (and not the others).

In our case it would generate this:
```
# @meilisearch/instant-meilisearch

## 0.11.0

### Minor Changes

- I did something

```

It also updates the version in the related package based on whether the changesets asked for a major, minor or patch update. In our case, we asked for a `minor` update, so the package.json of `@meilisearch/instant-meilisearch` has its version updated to `0.11.0`.

## Publish

Finally, based on the packages that saw their version updated, the publish function will only publish the affected packages.

## Process

We want users to not use `changeset publish` or `changeset version` locally. This should be handled by the CI. 
`changesets` has a [dedicated github action](https://github.com/changesets/action)to handle that.

In this action we want the following: 
- On each push to main, the CI should update a PR it created with the updated changelogs and versions. [Example](https://github.com/emotion-js/emotion/pull/2885)
- When the PR is merged, the CI should generate both a github release for the related packages ([see example](https://github.com/emotion-js/emotion/releases)) and publish then on `npm`. 

## Todo
- [ ] Add `changesets` configuration to the repo
- [ ] Update the contributing guide with the new required changeset that has to be added on every PR
- [ ] Update the publish CI to follow the process described above
- [ ] Handle pre-releases and beta versions

**Comment by bidoubiwa** [comment]
fixed by #965
